version: '3.8'
  
services:
  jupyter:
   image: jupyter/scipy-notebook 
   container_name: jupyter 
   ports:
    - 8888:8888
   working_dir: /home/jovyan
   volumes:
    - ./:/home/jovyan
   command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
   environment:
     JUPYTER_ENABLE_LAB: "yes"
   restart: "no"
